### ISSUE TITLE
TypeError: Not running in an Electron environment!

### ISSUE THREAD

**Issue by SomeBoringNerd** [luuxis/paladium-launcher-V8#2]
salut, après avoir clone le github, installé les dépendances Node, j'ai cette erreur en essayant de run le launcher.

![image](https://user-images.githubusercontent.com/40527889/173635798-a52d2637-63c1-4c33-a64f-3c36bb36674d.png)

Merci de la réponse !

**Comment by luuxis** [comment]
npm start 😀😀

**Comment by SomeBoringNerd** [comment]
merci, désolée de ma connerie lol
